-- Generated by the database client.
CREATE TABLE employees(
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    email varchar(255) NOT NULL,
    first_name varchar(255) NOT NULL,
    last_name varchar(255) NOT NULL,
    address_id bigint,
    PRIMARY KEY(id),
    CONSTRAINT fkkvaekcr8qinc0oo3kxwxgtyt9 FOREIGN key(address_id) REFERENCES addresses(id)
);
CREATE UNIQUE INDEX ukj9xgmd0ya5jmus09o0b8pqrpb ON public.employees USING btree (email);
CREATE UNIQUE INDEX ukrsvlaac3t8dn6ub004hsp8w91 ON public.employees USING btree (address_id);


-- Generated by the database client.
CREATE TABLE addresses(
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    city varchar(255),
    country varchar(255),
    state varchar(255),
    street varchar(255),
    zip_code varchar(255),
    employee_id bigint,
    PRIMARY KEY(id),
    CONSTRAINT fkn245yk1j248vwb8sxdcsu6eao FOREIGN key(employee_id) REFERENCES employees(id)
);
CREATE UNIQUE INDEX ukkt8rnnfcsl75nm85j2u9mb8qy ON public.addresses USING btree (employee_id);


-- Generated by the database client.
CREATE TABLE departments(
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    description varchar(255),
    location varchar(255),
    name varchar(255) NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX ukj6cwks7xecs5jov19ro8ge3qk ON public.departments USING btree (name);